# Site settings
name: Less Or More
email: 535819314@qq.com
author: zcb
url: https://github.com/zcbgit
resume_site: https://github.com/zcbgit
github: https://github.com/zcbgit
baseurl: ""
description: Actually, less is more!
meta_description: 个人笔记;个人博客;
motto: It's our wits that make us men.
banner: 记录知识，记录生活。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zcbgit
highlighter: rouge

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
